name: Hello Agile

on:
  push:
    branches: [test]
  pull_request: #Comment
    branches: [test]

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello from GitHub Actions!"
